
zuul:
  routes:
    user-service:
      path: /user-service/**
      url : http://localhost:8083


  ignored-services: *
  ignored-patterns: /**/admin/**

  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000


ribbon:
  eureka:
    enabled: false

server:
  port:8080
