server:
  port: 8093

spring:
  profiles:
    active: mysql
---
spring:
  profiles: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
      #ddl-auto: create
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/capston?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
---
#constant
openAPI:
  api: j9mhYBLjb2uQL9PFIhB1FKNUnu3t8AX0Mh7bO08M
  secret : 3fi41ArBAHryIE0BuCkm1xJCojVsmFRHMr3DHwiB
  state : 12345678901234567890123456789012

#linux:
#  keypath: /home/ftp_user/test-key.pem
